// 고정 4인 캐릭터 배경 데이터
export const BACKGROUNDS = [
  {
    id: 'analyst',
    label: '데이터 분석가',
    trait: '차분한',
    weakness: '숫자 없으면 불안함',
    weapon: '태블릿 PC',
    armor: '체크 셔츠',
    accessory: '명상 쿠션',
    emoji: '📊',
    description: '기술적 행동에 보정 (+2)',
  },
  {
    id: 'marketer',
    label: '마케팅 기획자',
    trait: '계획적인',
    weakness: '계획이 틀어지면 패닉',
    weapon: '마케팅 기획안',
    armor: '러닝 재킷',
    accessory: '스마트워치',
    emoji: '📋',
    description: '사회적 행동에 보정 (+2)',
  },
  {
    id: 'ceo',
    label: '스타트업 대표',
    trait: '자신감 넘치는',
    weakness: '투자 아이디어에 전투 집중력 저하',
    weapon: '유도복 띠',
    armor: '유도복 상의',
    accessory: '투자 제안서',
    emoji: '🥋',
    description: '창의적 행동에 보정 (+2)',
  },
  {
    id: 'reporter',
    label: '기자',
    trait: '본능적인',
    weakness: '특종 냄새에 분별력 상실',
    weapon: '복싱 글러브',
    armor: '트렌치코트',
    accessory: '녹음기',
    emoji: '🥊',
    description: '물리/방어 행동에 보정 (+2)',
  },
] as const;
